chore: fix indentation (#28)

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -5,7 +5,9 @@ on:
       - main
 env:
   ACTION_NAME: auto-merge-action
+
 jobs:
+  build:
   build: # make sure build/ci work properly
     runs-on: ubuntu-latest
     steps:
@@ -15,47 +17,47 @@ jobs:
       - run: |
           npm run build
           npm run test
-    - name: commit
-      run: |-
-        set -e
-        # get current commit hash
-        CURRENT_HASH=$(git rev-parse HEAD)
-        # get last commit hash of last build dist
-        LAST_BUILD_HASH=$(git log --author=google-github-actions-bot -1 --pretty=format:"%H")
-        DIFF=""
-        # build and commit dist if diff
-        git config --global user.name "kenhowardpdx[bot]"
-        git config user.email 'bot@github.kenhoward.dev'
-        git add dist/
-        git diff-index --quiet HEAD || git commit -m "chore: build dist ${ACTION_NAME}"
-        # if last commit hash of last build dist was found, get logs of commits in btw for PR body
-        if [ -z "$LAST_BUILD_HASH" ]
-        then
-              echo "Unable to find last commit by bot, skipping diff gen"
-        else
-              DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
-              echo $DIFF
-        fi
-        # set env vars
-        echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
-        echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
-        echo 'DIFF<<EOF' >> $GITHUB_ENV
-        echo "${DIFF}" >> $GITHUB_ENV
-        echo 'EOF' >> $GITHUB_ENV
-    - name: Create PR with dist
-      uses: peter-evans/create-pull-request@v3
-      with:
-        token: ${{ secrets.ACTIONS_BOT_TOKEN }}
-        commit-message: Build dist
-        author: "kenhowardpdx[bot] <bot@github.kenhoward.dev>"
-        title: "chore: build dist"
-        body: |
-          Build dist PR
-          ${{env.DIFF}}
-        labels: automated pr
-        branch: create-pull-request/build-dist
-        delete-branch: true
-        push-to-fork: kenhowardbot/${{env.ACTION_NAME}}
+      - name: commit
+        run: |-
+          set -e
+          # get current commit hash
+          CURRENT_HASH=$(git rev-parse HEAD)
+          # get last commit hash of last build dist
+          LAST_BUILD_HASH=$(git log --author=google-github-actions-bot -1 --pretty=format:"%H")
+          DIFF=""
+          # build and commit dist if diff
+          git config --global user.name "kenhowardpdx[bot]"
+          git config user.email 'bot@github.kenhoward.dev'
+          git add dist/
+          git diff-index --quiet HEAD || git commit -m "chore: build dist ${ACTION_NAME}"
+          # if last commit hash of last build dist was found, get logs of commits in btw for PR body
+          if [ -z "$LAST_BUILD_HASH" ]
+          then
+                echo "Unable to find last commit by bot, skipping diff gen"
+          else
+                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
+                echo $DIFF
+          fi
+          # set env vars
+          echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
+          echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
+          echo 'DIFF<<EOF' >> $GITHUB_ENV
+          echo "${DIFF}" >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
+      - name: Create PR with dist
+        uses: peter-evans/create-pull-request@v3
+        with:
+          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
+          commit-message: Build dist
+          author: "kenhowardpdx[bot] <bot@github.kenhoward.dev>"
+          title: "chore: build dist"
+          body: |
+            Build dist PR
+            ${{env.DIFF}}
+          labels: automated pr
+          branch: create-pull-request/build-dist
+          delete-branch: true
+          push-to-fork: kenhowardbot/${{env.ACTION_NAME}}
   auto-merge-action-release:
     needs: [build]
     runs-on: ubuntu-latest
